name: PR CI Build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    steps:
      - name: Setup .Net 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - uses: actions/checkout@v3
      - name: Restore
        run: dotnet restore --nologo
      - name: Build
        run: dotnet build --no-restore --nologo --configuration Release
      - name: Test
        run: dotnet test --nologo --no-build --configuration Release

  code-style:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Setup .Net 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Restore
        run: dotnet restore --nologo
      - name: Add .Net Format Problem Matcher
        shell: bash
        run: |
          echo "::add-matcher::${{ github.workspace }}/.github/dotnet-format-problem-matcher.json"
      - name: .Net Format
        id: format
        run: dotnet format --no-restore -v diag
      - name: Commit files
        #if: failure() && steps.format.outcome == 'failure'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"
